# Generated by Django 5.2.5 on 2026-05-12 03:41

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text='E.g. "Casa", "Oficina"', max_length=100
                    ),
                ),
                ("recipient_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("street", models.CharField(max_length=255)),
                ("street_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "country",
                    django_countries.fields.CountryField(default="PE", max_length=2),
                ),
                ("is_default_shipping", models.BooleanField(default=False)),
                ("is_default_billing", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Address",
                "verbose_name_plural": "User Addresses",
                "ordering": ["-is_default_shipping", "-created"],
            },
        ),
    ]
