"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

Quick-start development settings - unsuitable for production
See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
"""

from django.core.exceptions import ImproperlyConfigured
from .env import env, BASE_DIR

PROJECT_NAME = env('PROJECT_NAME', default='Test')

DOMAIN = env('DOMAIN', default='localhost')

FRONTEND_DOMAIN = env('FRONTEND_DOMAIN', default='http://localhost:5174')

SECRET_KEY = env('DJANGO_SECRET_KEY')

DEBUG = env('DEBUG', default=False)

IS_TEST = env('IS_TEST', default=False) # Use for simulating prod in local environment

DISABLE_REGISTRATION = env('DISABLE_REGISTRATION', default=False)

# API Documentation (enable in dev, disable in production for security)
ENABLE_API_DOCS = env('ENABLE_API_DOCS', default=DEBUG)

ALLOWED_HOSTS = [env('DOMAIN', default='localhost')]

# Container health checks and local dev always need localhost
ALLOWED_HOSTS += ['localhost', '127.0.0.1']

# Railway auto-injects this; allow the public Railway domain when present
_railway_domain = env('RAILWAY_PUBLIC_DOMAIN', default='')
if _railway_domain:
    ALLOWED_HOSTS.append(_railway_domain)

ENABLE_OTP_ADMIN = True
ADMIN_USER = env('ADMIN_USER', default='admin@admin.com')
_admin_masterpass = env('ADMIN_MASTERPASS', default='')
if not _admin_masterpass and not DEBUG:
    raise ImproperlyConfigured('ADMIN_MASTERPASS must be set in production (DEBUG=False).')
ADMIN_MASTERPASS = _admin_masterpass or '1234'  # safe default for DEBUG/testing only

# Opt-in OTP check on admin-gated API endpoints (REQUIRE_OTP_FOR_ADMIN_API=False by default)
REQUIRE_OTP_FOR_ADMIN_API = env('REQUIRE_OTP_FOR_ADMIN_API', default=False)

# Application definition

# Security headers
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
SECURE_SSL_REDIRECT = env('SECURE_SSL_REDIRECT', default=False)

# CSRF trusted origins — always include the frontend dev URL and the app domain
_extra_origins = [
    o.strip() for o in env('CSRF_TRUSTED_ORIGINS_EXTRA', default='').split(',') if o.strip()
]
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5174',
    'http://127.0.0.1:5174',
    f'https://{DOMAIN}',
    f'https://{FRONTEND_DOMAIN}',
] + _extra_origins

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'django.contrib.sitemaps',

    # REST API
    'rest_framework',
    'rest_framework.authtoken',
    # JWT refresh-token blacklist — required for BLACKLIST_AFTER_ROTATION
    # to actually invalidate the prior refresh token on rotation, and for
    # DELETE /api/users/me/ to blacklist outstanding tokens on soft-delete.
    'rest_framework_simplejwt.token_blacklist',

    # Auth
    'dj_rest_auth',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',  # needed, cause bug https://github.com/Tivix/django-rest-auth/issues/412
    'allauth.socialaccount.providers.google',
    'dj_rest_auth.registration',

    # Admin tools
    'admin_tools',
    'admin_tools.theming',
    'admin_tools.menu',
    'admin_tools.dashboard',

    # IP
    'django_user_agents',

    # Internal apps
    'core',
    'users',
    'products',
    'orders',
    'coupons',
    'marketing',

    'drf_spectacular',
    'django_filters',
    'django_countries',
    'corsheaders',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'rangefilter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.RequestIdMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # New
    # 'core.middleware.force_default_language_middleware', # New
    # 'core.middleware.SetupTranslationsLang', # New
    'corsheaders.middleware.CorsMiddleware', # New
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'core.middleware.AccessLogsMiddleware',  # Track access patterns and security events
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'maintenance_mode.middleware.MaintenanceModeMiddleware',  # Uncomment when maintenance mode is needed
    'core.middleware.ResponseTimeMiddleware',  # Monitor performance and potential DoS attacks

    # Odd
    'allauth.account.middleware.AccountMiddleware',
]



ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        # 'APP_DIRS': True,
        'OPTIONS': {
            'loaders': [
                'admin_tools.template_loaders.Loader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sites framework — required by allauth / socialaccount
SITE_ID = 1

# Static files configuration
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Optional: Configure OTP settings
# OTP_TOTP_ISSUER = 'Test'
# OTP_LOGIN_URL = '/admin/login/'

# HTTPS / HSTS / Secure cookie settings (production only)
if not DEBUG and not IS_TEST:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
