# Generated by Django 5.2.5 on 2026-03-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('hero', 'Hero'), ('anuncio', 'Anuncio'), ('categoria', 'Categoria')], max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('subtitulo', models.CharField(blank=True, max_length=255)),
                ('texto_cta', models.CharField(blank=True, max_length=100)),
                ('enlace_cta', models.URLField(blank=True)),
                ('imagen_url', models.URLField(blank=True)),
                ('imagen_movil_url', models.URLField(blank=True)),
                ('color_fondo', models.CharField(blank=True, max_length=20)),
                ('color_texto', models.CharField(blank=True, max_length=20)),
                ('posicion', models.IntegerField(default=0)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['posicion', '-created'],
                'indexes': [models.Index(fields=['tipo', 'es_activo'], name='marketing_b_tipo_617eb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Configuración de Tienda',
                'verbose_name_plural': 'Configuraciones de Tienda',
                'ordering': ['clave'],
                'indexes': [models.Index(fields=['clave'], name='marketing_c_clave_aea1f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('bienvenida', 'Bienvenida'), ('abandono_carrito', 'Abandono de Carrito'), ('intencion_salida', 'Intención de Salida'), ('suscripcion', 'Suscripción')], max_length=30)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('imagen_url', models.URLField(blank=True)),
                ('texto_cta', models.CharField(blank=True, max_length=100)),
                ('enlace_cta', models.URLField(blank=True)),
                ('codigo_cupon', models.CharField(blank=True, max_length=50)),
                ('retraso_segundos', models.IntegerField(default=3)),
                ('frecuencia_horas', models.IntegerField(default=24)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Popup',
                'verbose_name_plural': 'Popups',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['tipo', 'es_activo'], name='marketing_p_tipo_d6c838_idx')],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto Fijo'), ('compra_x_lleva_y', 'Compra X Lleva Y')], max_length=20)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra_cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('lleva_cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('aplica_a_todo', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('es_flash_sale', models.BooleanField(default=False)),
                ('limite_uso', models.PositiveIntegerField(blank=True, null=True)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('es_activo', models.BooleanField(default=True)),
                ('prioridad', models.IntegerField(default=0)),
                ('categorias', models.ManyToManyField(blank=True, related_name='promociones', to='products.category')),
                ('productos', models.ManyToManyField(blank=True, related_name='promociones', to='products.product')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-prioridad', '-created'],
                'indexes': [models.Index(fields=['es_activo', 'fecha_inicio', 'fecha_fin'], name='marketing_p_es_acti_083ef4_idx'), models.Index(fields=['slug'], name='marketing_p_slug_290649_idx')],
            },
        ),
    ]
