# Generated by Django 5.2.5 on 2026-05-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0004_backfill_translations"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "theme_id",
                    models.CharField(
                        choices=[
                            ("classic", "Clásico"),
                            ("dark", "Oscuro"),
                            ("elegant", "Elegante"),
                            ("nature", "Naturaleza"),
                            ("vibrant", "Vibrante"),
                            ("pastel", "Pastel"),
                            ("tech", "Tecnología"),
                            ("minimal", "Minimalista"),
                        ],
                        default="classic",
                        max_length=20,
                    ),
                ),
                ("custom_colors", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Tema del sitio",
                "verbose_name_plural": "Tema del sitio",
            },
        ),
    ]
