# Generated by Django 5.2.5 on 2026-04-29 01:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["-created"]},
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created"], name="order_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "-created"], name="order_status_created_idx"
            ),
        ),
    ]
