# Generated by Django 5.2.5 on 2026-05-16 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_refund_alter_orderitem_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("customer_payment_received", "Pago confirmado — cliente"),
                            (
                                "customer_status_update",
                                "Actualización de estado — cliente",
                            ),
                            ("customer_refund", "Reembolso procesado — cliente"),
                            (
                                "admin_new_paid_order",
                                "Nuevo pedido pagado — administrador",
                            ),
                            (
                                "admin_status_update",
                                "Actualización de estado — administrador",
                            ),
                            (
                                "admin_amount_mismatch",
                                "Alerta de monto incorrecto — administrador",
                            ),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("template_name", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("recipient_email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("retrying", "Reintentando"),
                            ("confirmed", "Confirmado"),
                            ("failed", "Fallido"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("task_args", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="orders.order",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(fields=["status"], name="emaillog_status_idx"),
                    models.Index(
                        fields=["email_type", "status"], name="emaillog_type_status_idx"
                    ),
                ],
            },
        ),
    ]
