# Generated by Django 5.2.5 on 2026-04-29 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productvariant",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="varianttype",
            options={"ordering": ["-created"]},
        ),
    ]
