# Generated by Django 5.2.5 on 2026-05-12 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_backfill_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="srcset_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="thumbnail_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="compare_at_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "-created"], name="product_active_created_idx"
            ),
        ),
    ]
